name: Check Elixir

on:
  push:
    branches:
      - main


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with: 
          otp-version: latest
          elixir-version: latest
      # - run: mix deps.get
      # - run: mix credo --strict